### ISSUE TITLE
Count down timer in wrong missions

### ISSUE THREAD

**Issue by JRH-1997** [KBOE2/LSS-Scripts#1]
The plug in shows timers in missions while there are missing vehicles. 
https://prnt.sc/shhth2

This is the Dutch version.

**Comment by KBOE2** [comment]
Yes, missions sometimes start as soon as single vehicles are on site.  And the script counts down how long the mission is going to be "prepped".

That's how it works:
For each mission in progress, the game executes a function every second.  In this function it is calculated when the mission stops being processed.  And that is when the mission is finished, or, if not everything needed is on site and the mission has already been started.

I use this calculated "end time" to calculate how far it is until then and then format the whole thing nicely.

That's why the clock is already running when the mission is not yet green.
